<?php
loadView('header', array('title' => $title, 'store_details' => $store_details));
?>

<div class="common-margin-top" id="top">
    <div class="page-margin">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-lg-12 col-xs-12">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="<?php echo $siteUrl;?>">Home</a></li>
                        <li class="breadcrumb-item">Terms &amp; Conditions</li>
                    </ol>
                </div>
            </div>
            <div class="aboutus-content">
                <h4 class="text-center">TERMS & CONDITIONS</h4>
                <p>Welcome to our website ("site"), owned and operated by Waverly Liquors., together with its subsidiaries and affiliates (which operate as an integrated business, generally doing business as “Waverly Liquors”.  By using our website, YOU AGREE TO BE BOUND BY THESE TERMS OF SERVICE, and all the terms, conditions, disclaimers and limitations that appear or are made available to you on our site (for example, in connection with special offers or promotions) and all of these, as they may be amended from time to time, we may refer to collectively as your "Agreement" with us. The policies that apply in our retail store may differ from those applicable to your use of our website and you should keep in mind these are separate and relate to different locations and platforms. We may refer to anyone using, registering, visiting or taking advantage of any of the features, functions, offers or links made available, on or through our website, as "you" or "your" in our Agreement and we may refer to Waverly Liquors. as Waverly Liquors, "we", "us" or "our" (or, of course "Waverly Liquors").</p>
                <h4>Acceptance of and Changes to Terms of Service</h4>
                <p>
By using our website and services, you signify your acceptance of the Agreement, including, without limitation, all the terms and conditions in these Terms of Service. If you do not agree completely with any terms, conditions, disclaimers, limitations or other provisions in your Agreement with us, your only remedy is to discontinue use of our Website. We reserve the right to modify our Agreement with you, including, without limitation, these Terms of Service at any time. Your continued use of any portion of our Website following the effective date contained in the notification or the posting of such changes on our Website if no other effective date is specified, will constitute your acceptance of those changes and agreement to comply with all the current terms and conditions of the Agreement.</p>
               <p>If you have questions or concerns about our specific terms, please send an e-mail to <a href="https://www.wliquors.com/" target_blank>wliquors@gmail.com</a>.</p>
                
<h4>User Obligations</h4>
<p>You agree not to do any of the following while using the wliquors.com Website or any of our sites:</p>
<ul class="pptt">
    <li>Intentionally or knowingly violate any applicable law or regulation, agreement that you are bound by – including this Agreement – nor the rights of any other party;</li>
    <li>Misrepresent or try to deceive us as to your identity or the identity of anyone else, use buying agents or conduct fraudulent activities;</li>
    <li>Exceed authorized access, tamper with, or misuse any areas of the <a href="https://www.wliquors.com/" target_blank>wliquors.com</a> site or <a href="https://www.wliquors.com/" target_blank>wliquors.com</a>'s computer systems, resources, programming, code or communications capabilities, nor any features or functions of our sites. Anyone who does so or attempts to do so may be subject to prosecution.</li>
    <li>Frame or link to the <a href="https://www.wliquors.com/" target_blank>wliquors.com</a> Site or any of our other sites, unless permitted in writing by <a href="https://www.wliquors.com/" target_blank>wliquors.com</a>.</li>
</ul>	
<h4>The Sale of Alcoholic Beverages</h4>
<p>We do not sell alcohol to persons under the age of 21 or anyone outside the United States (or even in the U.S if prohibited by law). By using this site you swear and affirm and represent to us that you are over the legal age required to buy alcoholic beverages and products and we will rely upon this representation because if we are held liable for any reason if that is not true, you agree to indemnify us and/or reimburse us and be responsible for all costs, expenses (including legal fees) and damages we suffer or incur. We make every effort to ensure that alcoholic beverages are not sold or delivered to anyone who is under the age of 21. By using this site you are acknowledging that the person receiving a shipment of alcoholic beverages from us is over the age of 21. You also agree that any alcohol purchased from us is intended for personal consumption and not for resale. If you cannot make these affirmations and representations or you do not agree with all of these conditions of use please do not use this site. If you intentionally or unintentionally misrepresent your age in order to obtain or provide alcohol to a person under the age of 21, we will report this to the appropriate authorities and prosecute you fully to the extent allowable by law.</p>
<h4>Title and Ownership</h4>
<p>
Title to, and ownership of, all alcoholic beverages passes from us to the purchaser at the store, in the State the alcoholic beverage is purchased, and it is the purchaser’s sole responsibility to ship and/or arrange for shipping from our store/warehouse to his/her home State. By arranging for transportation or shipping of any alcoholic beverage under your instructions, we are providing a service to, and acting on behalf of you, or the purchaser if another party. By having us arrange the shipping on your behalf, you are also representing that you are acting in a fashion compliant with the laws and regulations of your State, municipality and any others that apply to you regarding the purchase, shipping, transportation and delivery of alcoholic beverages, including, without limitation, wine. You affirm and represent that you have obtained any and all required permission or consent, paid any required fees, and are working through properly licensed intermediaries where required, and you, or the purchaser or other intended or actual recipient, is legally entitled to receive and take possession of alcoholic beverages, is legally entitled to the quantities ordered and delivered and once again represents that he/she is 21 years of age or older.</p>

<h4>Third Party Content and Monitoring</h4>
<p>Any opinions, advice, statements, services, offers, events or other information or content expressed or made available on our Website by any third parties (including information providers and users) are those of the respective author(s) or distributor(s) and not ours. We neither endorse nor are responsible for these, in any way, including, without limitation, the accuracy or reliability of any opinion, advice, information or statement made by anyone other than our employee who is authorized by us and is acting in her or his official capacity.</p>
<h4>Parental Control Protections</h4>
<p>

As required by the Communications Decency Act of 1996, we hereby notify you that parental control protections (such as computer hardware, software or filtering services) are commercially available that may assist you in limiting access to information and content that may be objectionable or harmful to minors as specified by law. Among the many companies that provide Internet blocking and screening software are CyberPatrol, NetNanny, SurfWatch and GuardOne. We do not sponsor or endorse or control any of these companies or their services.</p>
<h4>Links</h4>

<p>Our site may contain links to other websites and/or resources. You acknowledge and agree that we are not responsible or liable for their (1) availability or accuracy; or (2) content, advertising or products on or made available. The inclusion of any link on our site does not imply that we endorse, verify, have reviewed or monitor the link or the site reached through the link.</p>
<h4>Copyright Notice</h4>
<p>
All text, graphics, logos, icons, images, audio clips, video clips and software on the site ("Content") are copyrighted materials owned by or licensed to us. Content may contain trademarks, service marks and trade names which are owned by us and may also contain brand and product names which are trademarks, service marks or trade names which are owned us or by third parties and the term "Content" will be used and mean to include these as well. Unless authorized in writing by an officer of Waverly Liquors, you may not use any Content without our consent and even if we consent, in any manner that is likely to cause confusion among customers, or in any manner that disparages or discredits us. You may not sell, reproduce, distribute, copy, duplicate, resell, modify, display, publicly perform, prepare derivative works based on, frame, mirror, repost, exploit for any commercial purpose, or otherwise use any of the Content in any way for any public or commercial purpose without our prior written consent or the consent of the rights holder if not us. You may not use the Content on any other website or medium. You may not use the Content in a networked computer environment for any purpose other than to transact with our site as authorized by us. If you violate any of these terms, your permission to use the Content will automatically terminate, you must immediately destroy Content in your possession or under your control and any copies you have made and we may end your authorization to use our site. Nothing shall be construed as conferring any license or right under any copyright, trade secret, patent, trademark or other intellectual property rights to you and we expressly reserved all such rights.</p>
<h4>Notices</h4>

<p>"Communication" means any customer agreements or amendments thereto, disclosures, notices, responses to claims, transaction history, privacy policies and all other information related to your use of the site, including but not limited to information that we are required by law to provide to you in writing. We will give you any necessary Communications by posting them on our site. You authorize us to send any Communications and all changes to such Communications electronically. You must provide at your own expense an Internet connected device that is compatible with the minimum requirements outlined below. You also confirm that your device will meet these specifications and requirements and will permit you to access and retain the Communications electronically each time you access and use the applicable services.</p>
<p>Please select Print, and select your printer to retain a copy. If you do not have a printer, you can copy the text of this Disclosure and the underlying agreements and paste the text into a new document in a word processor or a text editor on your computer and save the text.</p>

<h4>SYSTEM REQUIREMENTS TO ACCESS INFORMATION</h4>
<p>To receive and view an electronic copy of the Communications you must have the following equipment and software:</p>
<ul class="pptt">
    <li>A personal computer or other device which is capable of accessing the Internet. Your access to this page verifies that your system/device meets these requirements.</li>
    <li>An Internet web browser which is capable of supporting 128-bit SSL encrypted communications, JavaScript, and cookies. Your system or device must have 128-bit SSL encryption software. Your access to this page verifies that your browser and encryption software/device meet these requirements.</li>
</ul>
<h4>SYSTEM REQUIREMENTS TO RETAIN INFORMATION</h4>	
<p>
To retain a copy, you must either have a printer connected to your personal computer or other device or, alternatively, the ability to save a copy through use of printing service or software such as Adobe Acrobat®. If you have a word processor or text editor program on your computer, then you can also copy the text of this Disclosure and the underlying agreements and paste the text into a new document in the word processor or text editor and save the text.</p>
<h4>WITHDRAWAL OF ELECTRONIC ACCEPTANCE OF DISCLOSURES AND NOTICES</h4>
<p>
You can also contact us in any of the ways described in the paragraph entitled "Paper Delivery of Disclosures and Notices" to withdraw your consent to receive any future Communications electronically, including if the system requirements described above change and you no longer possess the required system. If you withdraw your consent, we will terminate your use of the site and the services provided through the site.</p>
<h4>TERMINATION / CHANGES</h4>
<p>We reserve the right, in our sole discretion, to discontinue the provision of your electronic Communications, or to terminate or change the terms and conditions on which we provide electronic Communications. We will provide you with notice of any such termination or change as required by law.</p>
<h4>Disclaimer of Warranties</h4>
<p>Although we endeavor to provide current, accurate and reliable information on our site, we cannot and do not warrant, promise, guarantee or make any representations regarding the accuracy, security, reliability or any use of the functions, features, operations, Content or information. We cannot and do not warrant your use of our site, or the operation or function of the our site, any component, feature, function, capability or offer or any products, software or services, will be uninterrupted or error free, or that defects or malfunctions will be corrected or that the site is free of viruses or other harmful elements.</p>
<p>Your use of our site is solely and fully at your own risk and you assume full responsibility for all costs and expenses associated with servicing and/or repair in any way connected or arising from attempted, alleged or actual use or access of our site. We make no representations about the suitability, reliability, availability, timeliness and accuracy of the our site. OUR SITE AND THE CONTENT IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT ANY EXPRESS, IMPLIED OR STATUTORY WARRANTY OF ANY KIND INCLUDING WARRANTIES OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT OF THIRD PARTY RIGHTS, OR FITNESS FOR ANY PARTICULAR PURPOSE.</p>
<h4>Limitation of Liability</h4>
<p>In no event shall we and/or our officers, directors, partners, owners, agents, contractors, representatives and/or be liable to you or anyone else for any indirect, punitive, incidental, special or consequential damages or any damages whatsoever, including, without limitation, damages for loss of use, data or profits, arising out of or in any way connected with our website, this Agreement, the use or performance of our website, the delay or inability to use our website, the provision of or failure to provide services, or for any events, information, software, products, services and related graphics obtained through the our website, or otherwise arising out of the use of our website, whether based on contract, tort, negligence, strict liability or otherwise, even if we or any other party may have been advised of the possibility of damages.</p>
<p>
If you are dissatisfied with any portion of our website, or with any part of this Agreement or your transactions with us, your sole and exclusive remedy is to discontinue using our website. This sole and exclusive remedy is separate and independent of any other provision that limits our liability or your remedies under this Agreement.</p>
<h4>Indemnity</h4>
<p>You agree to defend, indemnify, and hold Waverly Liquors, its affiliates, employees, officers, and agents ("Waverly Liquors Parties") harmless from and against any and all claims, damages, losses, costs, investigations, liabilities, judgments, fines, penalties, settlements, interest and expenses (including attorneys’ fees) that directly or indirectly arise from or are related to any claim, suit, action, demand, or proceeding made or brought against any Waverly Liquors Party, or on account of the investigation, defense, or settlement thereof, arising out of or in connection with, whether occurring heretofore or hereafter: (i) any content you post or upload on the site; (ii) your use of the site and your activities in connection with the site; (iii) your breach or alleged breach of these Terms or any Additional Terms; (iv) your violation or alleged violation of any laws, rules, regulations, codes, statutes, ordinances or orders of any governmental or quasi-governmental authorities in connection with your use of the site or your activities in connection with the site; (v) information or material transmitted through your device used to access the site, even if not submitted by you, that infringes, violates or misappropriates any copyright, trademark, trade secret, trade dress, patent, publicity, privacy, or other right of any person or entity; (vi) any misrepresentation made by you; and (vii) Waverly Liquors Parties’ use of the information that you submit to us (all of the foregoing, "Claims and Losses"). You will cooperate as fully required by Waverly Liquors Parties in the defense of any Claim and Losses. Notwithstanding the foregoing, Waverly Liquors Parties retain the exclusive right to settle, compromise and pay any and all Claims and Losses. Waverly Liquors Parties reserve the right to assume the exclusive defense and control of any Claims and Losses. You will not settle any Claims and Losses without, in each instance, the prior written consent of an officer of a Waverly Liquors Party.</p>
<h4>Privacy Policy</h4>
<p>Your use of our website is also subject to our Privacy Policy.</p>
<h4>Validating Your Order</h4>
<p>After you place an order using our shopping cart, we will check the information you give us for validity and compliance with state laws and regulations, by verifying your method of payment or shipping address. We reserve the right to reject any order you place with us, and/or to limit quantities on any order, without giving any reason. If we reject your order, we will attempt to notify you using the e-mail address you have given us with the order. Your credit or debit card will normally not be charged if we reject an order, but we will process a refund if the charge has been made against your card.</p>
<h4>Order Acceptance/Confirmation</h4>
<p>Your receipt of an electronic or other form of order confirmation does not signify our acceptance of your order, nor does it constitute confirmation of our offer to sell. The Waverly Liquors website reserves the right at any time after receipt of your order to accept or decline your order for any reason.</p>
<h4>Return Policy</h4>
<p>All sales made through our website are subject to our return policy. For a complete description and explanation of our return policy, please see the section about Returns in our Customer Service section.</p>
<h4>Order Limitations</h4>
<p>We reserve the right to reject any order you place with us and/or or to limit quantities in any order, without giving any reason or for no reason, if we determine it is in our best interests to do so. If we reject your order or reduce the quantities of any items in your order, we will attempt to notify you using the e-mail and/or billing address you gave us when you placed the order.</p>

<h4>Order Limitations/Limited Quantities</h4>
<p>We may, at our own discretion, limit or cancel quantities purchased per person, per household or per order. We also reserve the right to reject any order you place with us. These restrictions may include orders placed by the same website account, the same credit card, and orders that use the same billing and/or shipping address. In the event we make a change to an order, we will attempt to notify you by contacting the e-mail and/or billing address provided at the time the order was made. We reserve the right to limit or prohibit sales to dealers.</p>

<h4>Shipping</h4>
<p>We do not currently ship any products.</p>
<h4>In-Store or Curbside Pickup</h4>
<p>
As mentioned above, all orders are subject to product availability and will be available for pickup at our store (as designated in the order) according to our pickup policies. We will use the email address provided with the order to contact you when your order is ready for pickup. At pickup, the person who placed the order must be present and display valid State or government issued identification along with the credit card used as payment for the order. If after 14 days the order has not been picked up by the customer, we will attempt to notify you by contacting you with the information provided at the time the order was made. We reserve the right to cancel the order, return the products or other goods, and if we do that, to issue a credit to your credit card account (the one used to place the order) in the amount of the charge corresponding to the intended purchase. Individual bank policies will dictate when this amount is credited to your account.</p>
<h4>Errors on Our Site</h4>

<p>Prices and availability of products and services are subject to change without notice. Errors will be corrected where discovered and we have the right to refuse or cancel any orders placed for products and/or services listed at an incorrect price, rebate or refund or other promotional offer or containing any incorrect information or typographical errors. We have the right to refuse or cancel any such orders, whether or not the order has been confirmed and/or your credit card charged. If your credit card has already been charged for the purchase and your order is canceled, we shall issue a credit to your credit card account in the amount of the charge. Individual bank policies will dictate when this amount is credited to your account.</p>
<h4>
Mobile and Mobile Apps</h4>
<p>
    <a href="https://www.wliquors.com/" target_blank>Wliquors.com</a> may offer areas and features which are accessible via a mobile device, like a smartphone. These features and areas may include the ability to upload content, make purchases, determine your location, and other similar activities. Note that standard messaging, data, and other fees may be charged by your carrier to engage in any activities which are available on your mobile device. If you have questions about these issues, please contact your carrier as We have no control, and are not responsible for such charges.
    You agree that for the functions or services which are part of your registration with wliquors.com, We may send communications to your mobile device regarding the functions or services you have registered to be able to use on <a href="https://www.wliquors.com/" target_blank>wliquors.com</a>. You also agree that we may collect information related to your mobile device associated with your use of the features and areas which are accessible by your mobile device.</p>
    <h4>MOBILE TERMS OF USE</h4>
    <p>
Welcome to Waverly Liquor’s Mobile Alert Program (the "Program"), which includes, but is not limited to, Waverly Liquor’s Recurring Offers, transactional SMS/text alerts, and one-time text offers. Please review these Mobile terms of use ("Mobile Terms of Use"), which describe our Program and available codes and govern your use of the Program. BY ACCESSING, BROWSING, OR USING THE PROGRAM, YOU ACKNOWLEDGE AND AGREE THAT: (1) YOU ARE THE CURRENT SUBSCRIBER OR CUSTOMARY USER OF THE MOBILE PHONE NUMBER YOU PROVIDED TO Waverly Liquors IN ORDER TO PARTICIPATE IN THE PROGRAM; AND (2) YOU HAVE READ, UNDERSTAND, AND AGREE TO BE BOUND BY ALL THESE TERMS. IF YOU DO NOT AGREE TO THESE TERMS THEN PLEASE DO NOT USE THE PROGRAM. You are also subject to and agree to comply with Waverly Liquors  general Terms of Use located on this page.</p>

<p>PLEASE NOTE: You agree that if the mobile telephone number you provide as part of Waverly Liquors Recurring Offers at any time becomes reassigned, terminated or otherwise no longer your current mobile telephone number, you will PROMPTLY NOTIFY Waverly Liquors of any such reassignment or termination by calling (631) 941-3103 or by sending an email to <a href="mailto:wliquors@gmail.com">wliquors@gmail.com</a>.</p>
<h4>Termination of Use</h4>
<p>We may terminate your wliquors.com Account with or without cause at any time effective immediately. You are personally liable for any orders that you place or charges that you incur prior to termination. Us reserves the right to change, suspend or discontinue all or any aspects of the Us website at any time without prior notice.</p>
<h4>Force Majeure</h4>
<p>We shall be excused from performance under this Terms of Service if we fail or are prevented, forbidden or delayed from performing by reason of: (a) any provision of any present or future law or regulation or order of any court, the United States of America, or any State or local government body, (b) any act or omission of a third party, or (c) any act, emergency condition, war, computer or telecommunications failure or other circumstance beyond our control.</p>
<h4>General Provisions</h4>
<p>You agree that we and our agents, representatives, contractors, suppliers and others working on our behalf, may make improvements and/or changes in the Content on our site, and all features, functions and/or services may change at any time without notice and without liability of any kind. You are responsible for compliance with applicable laws and regulations that apply to you, keeping in mind that access to our site may not be legal by certain persons or in certain countries. Even if we don’t exercise some right or enforce some provision at any particular time, that doesn’t mean we have waived that or any other right in any way. If any provision of our Agreement is held by a court of competent jurisdiction to be contrary to law, then such provision shall be construed, as nearly as possible, to reflect the intentions of the parties, with all other provisions remaining in full force and effect. These Terms of Service, along with our Privacy Policy and any other terms, conditions or provisions specifically referred to herein, comprises the entire agreement between you and us regarding the subject matter and supersedes all prior or contemporaneous negotiations, discussions or agreements, if any, between the parties with respect to same. These Terms of Service and our Agreement with you, is personal to you and you may not transfer, assign, or delegate any of them to anyone without our express written permission and any attempt to do so without prior written permission, will be void ab initio. These Terms of Service will inure to the benefit of our successors, assignees, and licensees. The headings are included for reference only and have no effect on the meaning of any provision. Maryland and controlling U.S. federal law, without regard to the choice or conflicts of law provisions of any jurisdiction, will govern any action related to these Terms of Service and our Agreement with you. You agree to submit to the personal jurisdiction of the courts located in the State of Maryland, for the resolution of all disputes arising from or related to these Terms of Service, our Agreement with you and/or your use of the Site.</p>

                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>

<?php
loadView('footer', array('store_details' => $store_details, 'store_home_details'=>$store_home_details));
?>